AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template for creating IAM role and OIDC provider for Github Actions to assume to execute cert renewal
Resources:
  GithubIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: IcsiItGithubOidcRoleForCertRenewal
      Description: Role for Github Actions to assume to execute limited certbot actions and cloudformation operations
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref OIDCProvider
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: repo:icsi-it/cert-renewal:*
      Policies:
        - PolicyName: GithubActionsCloudformationAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStack*
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:CancelUpdateStack
                  - cloudformation:RollbackStack
                  - cloudformation:DescribeChangeSet*
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:ExecuteChangeSet
                Resource: !Sub arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/IcsiItCertRenewal/*
              - Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                Resource: '*'
        - PolicyName: GithubActionsCertbotRoute53
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:*
                Resource: !Sub arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:IcsiItCertbot*
              - Effect: Allow
                Action:
                  - iam:GetRole*
                  - iam:CreateRole*
                  - iam:PutRole*
                  - iam:DeleteRole*
                  - iam:List*
                  - iam:AttachRole*
                  - iam:PassRole*
                Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/certbot-github-actions-role*
              - Effect: Allow
                Action:
                  - iam:GetPolicy*
                  - iam:CreatePolicy*
                  - iam:PutPolicy*
                  - iam:DeletePolicy*
                  - iam:List*
                Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/certbot-dns-route53-policy*
              - Effect: Allow
                Action:
                  - route53:ListHostedZones
                  - route53:GetChange
                Resource: '*'
              - Effect: Allow
                Action:
                  - route53:ChangeResourceRecordSets
                Resource: !Sub arn:${AWS::Partition}:route53:::hostedzone/Z07864873ICJTWYGL9BNA*
  
  OIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      # The repeating f's are deliberate and not a placeholder/mistake. See:
      # https://github.com/aws-actions/configure-aws-credentials?tab=readme-ov-file#configuring-iam-to-trust-github
      # and: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html
      ThumbprintList:
        - ffffffffffffffffffffffffffffffffffffffff